### ISSUE TITLE
False positive

### ISSUE THREAD

**Issue by mathertel** [GitGuardian/gg-shield#12]
As an example I have a key in my doku repo, but it's invalid. (and I mentioned it).
Now I get a false positive alert.

Please provide details how to handle this when using gg-shield to avoid false positives.

**Comment by ericfourrier** [comment]
You can put the false positive key in the .gitguardian.yaml under `matches-ignore`. You can have more details [here](https://github.com/GitGuardian/gg-shield#configuration).

Don't hesitate if you have more questions
