### ISSUE TITLE
automatic pull request 

### ISSUE THREAD

**Issue by yuceltoluyag** [GitGuardian/gg-shield#16]
does the software find errors, but why not create an automatic pull request for the fix?

![alt text](https://i.ibb.co/m0dL4Tw/Screenshot-1.png "fix")

**Comment by Jguer** [comment]
Hey @yuceltoluyag ,

Just adding a commit removing your credentials will keep them in your git history, which not everyone may want (for example: even if you rotate your SMTP server credentials people will still know your service uses that SMTP host).
Just rewriting git history may not be desirable as well for some users.

With `ggshield` we leave it up to the user to decide how to handle the leak and focus on detecting the issue as early as possible. 

You may check our [Leak Mitigation Checklist](https://github.com/GitGuardian/APISecurityBestPractices/blob/master/Leak%20Mitigation%20Checklist.md) for some advice on how to handle the exposed credentials.
