### ISSUE TITLE
False Positive

### ISSUE THREAD

**Issue by threax** [GitGuardian/gg-shield#18]
Hello,

I have a repository that was reported with a false positive by your tool.

https://github.com/threax/Threax.Pipelines/commit/e8469b820c415ea05469731ba20e35d7a1d384a9#diff-e44d6862ce5abdbd548f53f8aa1e02acR93

This is not a problem. I have a function that builds connection strings with this inside. You should address this with your tool in some fashion. The YOU HAVE A SECURITY PROBLEM spam wasn't much appreciated.

Thanks,
Andrew

**Comment by GG-HH** [comment]
Hi @threax,
We are sorry that you received a false positive alert. 
We thank you very much for your feedback which will help us improve our algorithm.
