### ISSUE TITLE
RFE: CLI Argument That Reports Version Number

### ISSUE THREAD

**Issue by rgajason** [GitGuardian/gg-shield#51]
I'd like to request that a CLI argument be added to `ggshield` that will return version information.

**Comment by rgajason** [comment]
Turns out that everything needed is already included - just need to activate this in Click.

I opened https://github.com/GitGuardian/gg-shield/pull/54 for implementation.

**Comment by Jguer** [comment]
Implemented in #54, thanks for the help :smile:
