### ISSUE TITLE
Unreachable URL in email alert

### ISSUE THREAD

**Issue by liaojack8** [GitGuardian/gg-shield#8]
![image](https://user-images.githubusercontent.com/23449425/86108370-a965db00-baf5-11ea-9713-5a13cb35d08f.png)
I got the this email today, when I click ["Generic Private Key"](http://email.mail.gitguardian.com/c/eJzFUk2P2yAQ_TXxZZVoBoMxBx821XoPK7U99G6NYbBp_CWWpMq_L4ml9tpbEYzmCc3Mew9cA1JiX9AWLnzvxjCMUz6JXXeNUzOmtH0eyteDaPMeQhqv_cmucwZToPUn2Uud85b6GOwRv8UBv4y0LDwdv3L6tcbLXpZjrpqfCRrBEkpfWQOVlTVItqRK6j36sgLZk0XvvChCI0AAVEJDjVrhCU-qNW8C3lp5lqjUuT1ImClMpzxiuFJ0gZYHvSLxvE2UuFto5uYP2uLc3UTxn3XxjZfUuQchv8aZUnb7KfUI1VHoH1BnZihykPogzpBXQRPH1AXXKA_SWOo1GQeVROiVBiRF6Lwl4SVKrH0tMwXsfQUkpHKsPQtVl0a4IjZ_FUoIdlqvbves2eLqOupviE8Qbg-Kj28x8MLZiGJsEKoalDDMpTYgmLRVlWZUFoyUhgvHiW1aY-fCZzb9vr_A-97g5fve9OWD70Xkbd1v_9Hy3yrq23Y).
I got 404 error, the link redirection to [here](https://github.com/liaojack8/Fabric-1Org1Channel-Network/git/commit/192e403f6c906c4804eca53abf1f3604bac1fdf2), but the correct page is [here](https://github.com/liaojack8/Fabric-1Org1Channel-Network/git/commit/192e403f6c906c4804eca53abf1f3604bac1fdf2).

**Comment by GG-HH** [comment]
Hello @liaojack8 ,
Thanks a lot for your feedback! Indeed, there was a display issue with the URL (that have been fixed now). The url you should have had is [this one](https://github.com/liaojack8/Fabric-1Org1Channel-Network/commit/192e403f6c906c4804eca53abf1f3604bac1fdf2#diff-8eb9b57764c58f2abc1a8ee704d26664R1).
I have seen that you have committed multiple private keys and certificates and hope those are not used in ANY open server. If it is the case, I strongly encourage you to change those keys and use our [mitigation checklist](https://github.com/GitGuardian/APISecurityBestPractices/blob/master/Leak%20Mitigation%20Checklist.md) to ensure proper security.
