### ISSUE TITLE
Not all base64-encoded strings are azure keys

### ISSUE THREAD

**Issue by djmitche** [GitGuardian/gg-shield#9]
https://github.com/djmitche/taskcluster/commit/508879f341d47fc55c64805f55e4fdcdfffb6719#diff-6bec6ff2931ad8ff63611cd4919dd43eL810 is a 64-byte base64-encoded value produced by hmac with sha512.  It's not an Azure storage account key, as is the case for the vast majority of 64-byte base64-encoded values.  This is a false positive.

**Comment by GG-HH** [comment]
Hi @djmitche ,
Thanks a lot for your feedback, I am sorry that you received an email for a false positive.  
I am currently working with the secrets detection team to improve our algorithm based on your feedback. I can assure you that the algorithm was triggered by multiple elements and not only by the presence of a base64-encoded value.

**Comment by consideRatio** [comment]
For reference: #5 was also a false positive for an: azure storage account key.

Mozilla/sops had been used to encrypt a secret string.
